### ISSUE TITLE
Create a button or change the font size for the link to the event bright page at the bottom of the page. 

### ISSUE THREAD

**Issue by aplannersguide** [openchattanooga/citycampcha#1]

**Comment by seabre** [comment]
Ah. Thanks for reminding me!

**Comment by seabre** [comment]
@jden suggested moving this to the top along with making it a button.

**Comment by junosuarez** [comment]
this :cat2:

**Comment by seabre** [comment]
Added button to RSVP as part of call to action.

Also changed link to button and moved it down on the bottom.

**Comment by junosuarez** [comment]
:+1:

**Comment by seabre** [comment]
Got the thumbs up from @kylegordy andf @jden. @aplannersguide if you absolutely hate this, re-open.
